name: build-docker-image

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  
env:
  IMAGE_NAME: print 
  DOC_USER: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOC_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  TAG: ${{ github.sha }}
  IMAGE_PATH_1: ./Dockerfile
  IMAGE_PATH_2: ./DockerFile-2

jobs:
  test-workflows:
    name: Workflow for -> ${{ matrix.user.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          [
           {
             name: first-image,
             metadata:
                {
                  file: $IMAGE_PATH_1,
                }
           },    
            {
              name: sec-image,
              metadata:
                {
                  file: $IMAGE_PATH_2,
                }
            }
          ]    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build & Push Docker Image
        run: |
          echo "$DOC_PASS" | docker login -u "$DOC_USER" --password-stdin
          docker image build -t $DOC_USER/$IMAGE_NAME:$TAG -f ${{ matrix.user.metadata.file }} .
          docker push $DOC_USER/$IMAGE_NAME:$TAG
          
 #     - name: Trigger next workflow
  #      uses: convictional/trigger-workflow-and-wait@v1.3.0
   #     with:
    #      owner: cloudsky13
     #     repo: DevOps-Assignment
      #    github_token: ${{ secrets.GIT_TOKEN }}
       #   workflow_file_name: tag-workflow.yml
      - name: Trigger next workflow using Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: cloudsky13/Downstream-Repo
          event-type: custom-event
          client-payload: >
            {"component":
              {
                "name":"${{ matrix.user.name }}"
              }
            }  




