name: build-docker-image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: print-text 
  DOC_USER: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOC_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build & Push Docker Image
        run: |
          echo "${{ secrets.DOC_PASS }}" | docker login -u "$DOC_USER" --password-stdin
          docker image build -t DOC_USER/print:$GITHUB_RUN_NUMBER .
          docker push DOC_USER/print:$GITHUB_RUN_NUMBER
