name: build-docker-image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  IMAGE_NAME: print 
  DOC_USER: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOC_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  TAG: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build & Push Docker Image
        run: |
          echo "$DOC_PASS" | docker login -u "$DOC_USER" --password-stdin
          docker image build -t $DOC_USER/$IMAGE_NAME:$TAG .
          docker push $DOC_USER/$IMAGE_NAME:$TAG
          
 #     - name: Trigger next workflow
  #      uses: convictional/trigger-workflow-and-wait@v1.3.0
   #     with:
    #      owner: cloudsky13
     #     repo: DevOps-Assignment
      #    github_token: ${{ secrets.GIT_TOKEN }}
       #   workflow_file_name: tag-workflow.yml
      - name: Trigger next workflow using Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: cloudsky13/Downstream-Repo
          event-type: custom-event




