name: build-docker-image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: print 
  DOC_USER: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOC_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build & Push Docker Image
        run: |
          echo "$DOC_PASS" | docker login -u "$DOC_USER" --password-stdin
          docker image build -t $DOC_USER/$IMAGE_NAME:$GITHUB_RUN_NUMBER .
          docker push $DOC_USER/$IMAGE_NAME:$GITHUB_RUN_NUMBER
      - name: Trigger next workflow to print tag
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: cloudsky13
          repo: DevOps-Assignment
          github_token: ${{ secrets.GIT_TOKEN }}
          workflow_file_name: tag-workflow.yml




